services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - boilerplates-db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    image: node:20.11.1-alpine
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

volumes:
  boilerplates-db:
